name: gitartwork from a contribution graph

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: jasineri/gitartwork@v1
        with:
          user_name: ${{ github.repository_owner }}
          text: PULKIT
      - uses: jasineri/simple-push-action@v1
        with:
          repository: ${{ github.repository }}
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}